version: '3'
services:
  task:
    &base
    build: ./support/Dockerfile
    tty: true
    stdin_open: true
    command: ruby task.rb
    volumes:
        - ./:/task/

  test:
    <<: *base
    command: rspec test.rb
